### ISSUE TITLE
Support for newer js_of_ocaml and ocaml versions

### ISSUE THREAD

**Issue by dboris** [johnelse/ocaml-webtest#9]
Would be nice to update the dependencies to support newer js_of_ocaml versions. Currently:
webtest → js_of_ocaml < 3.0 → ocaml < 4.05.0

**Comment by johnelse** [comment]
Good idea! I'm pretty sure all it needs is a new release, I'll get that sorted :+1:

**Comment by johnelse** [comment]
https://github.com/ocaml/opam-repository/pull/16461

**Comment by dboris** [comment]
Thank you!

**Comment by johnelse** [comment]
No problem, enjoy!
